version: '3.8'

services:
  user_db:
    image: postgres:16
    container_name: user_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1 -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://user_db:${DB_PORT}/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./app/keycloak:/opt/keycloak/data/import
    depends_on:
      - user_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - app-net

  userservice:
    build: .
    container_name: userservice_app
    restart: unless-stopped

    depends_on:
      - user_db
      - keycloak
      - minio

    env_file:
      - .env

    environment:
      DB_HOST: user_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASS: ${KEYCLOAK_ADMIN_PASS}

      APP_PORT: ${APP_PORT}

      USER_SERVICE_TOKEN: ${USER_SERVICE_TOKEN}
      NOTIFICATION_SERVICE_TOKEN: ${NOTIFICATION_SERVICE_TOKEN}


    ports:
      - "${APP_PORT}:${APP_PORT}"
    
    expose:
      - "9090"
    
    # Start de binary
    command: ["./userservice"]

    networks:
      - app-net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-net

volumes:
  user_db_data:
  minio_data:

networks:
  app-net:
    external: true
